### ISSUE TITLE
Erro deploying main script: MDSYS.SDO_GEORASTER & MDSYS.SDO_RASTER must be declared 

### ISSUE THREAD

**Issue by eyp** [pauldzy/DZ_SDOTXT#7]
I'm trying to run the deployment SQL script in Oracle 11.2g, but I'm getting these errors:

Types/DZ_SDOTXT_LABELED.tps

Type DZ_SDOTXT_LABELED compiled

Grant succeeded.

Types/DZ_SDOTXT_LABELED.tpb

Type Body DZ_SDOTXT_LABELED compiled

Collections/DZ_SDOTXT_LABELED_LIST.tps

Type DZ_SDOTXT_LABELED_LIST compiled

Grant succeeded.

Packages/DZ_SDOTXT_UTIL.pks

Package DZ_SDOTXT_UTIL compiled

Grant succeeded.

Packages/DZ_SDOTXT_UTIL.pkb

Package Body DZ_SDOTXT_UTIL compiled

Packages/DZ_SDOTXT_MAIN.pks

Package DZ_SDOTXT_MAIN compiled

LINE/COL  ERROR
--------- -------------------------------------------------------------
103/4     PL/SQL: Declaration ignored
104/31    PLS-00201: identifier 'MDSYS.SDO_GEORASTER' must be declared
108/4     PL/SQL: Declaration ignored
109/31    PLS-00201: identifier 'MDSYS.SDO_RASTER' must be declared
Errors: check compiler log

Grant succeeded.

Packages/DZ_SDOTXT_MAIN.pkb

Package Body DZ_SDOTXT_MAIN compiled

LINE/COL  ERROR
--------- -------------------------------------------------------------
0/0       PL/SQL: Compilation unit analysis terminated
1/14      PLS-00905: object TRACESNT.DZ_SDOTXT_MAIN is invalid
1/14      PLS-00304: cannot compile body of 'DZ_SDOTXT_MAIN' without its specification
Errors: check compiler log
Types/DZ_SDOTXT_DUMPER.tps

Type DZ_SDOTXT_DUMPER compiled

Grant succeeded.

Types/DZ_SDOTXT_DUMPER.tpb

Type Body DZ_SDOTXT_DUMPER compiled

LINE/COL  ERROR
--------- -------------------------------------------------------------
135/16    PL/SQL: Statement ignored
136/19    PLS-00905: object TRACESNT.DZ_SDOTXT_MAIN is invalid
145/16    PL/SQL: Statement ignored
145/44    PLS-00905: object TRACESNT.DZ_SDOTXT_MAIN is invalid
310/16    PL/SQL: Statement ignored
310/44    PLS-00905: object TRACESNT.DZ_SDOTXT_MAIN is invalid
325/16    PL/SQL: Statement ignored
325/44    PLS-00905: object TRACESNT.DZ_SDOTXT_MAIN is invalid
Errors: check compiler log
Packages/DZ_SDOTXT_TEST.pks

Package DZ_SDOTXT_TEST compiled

Grant succeeded.

Packages/DZ_SDOTXT_TEST.pkb

Package Body DZ_SDOTXT_TEST compiled

Errors for TYPE BODY TRACESNT.DZ_SDOTXT_DUMPER:

LINE/COL ERROR
-------- -----------------------------------------------------------------
135/16   PL/SQL: Statement ignored
136/19   PLS-00905: object TRACESNT.DZ_SDOTXT_MAIN is invalid
145/16   PL/SQL: Statement ignored
145/44   PLS-00905: object TRACESNT.DZ_SDOTXT_MAIN is invalid
310/16   PL/SQL: Statement ignored
310/44   PLS-00905: object TRACESNT.DZ_SDOTXT_MAIN is invalid
325/16   PL/SQL: Statement ignored
325/44   PLS-00905: object TRACESNT.DZ_SDOTXT_MAIN is invalid

Error starting at line : 3,168 in command -
DECLARE
   l_num_errors PLS_INTEGER;

BEGIN

   SELECT
   COUNT(*)
   INTO l_num_errors
   FROM
   user_errors a
   WHERE
   a.name LIKE 'DZ_SDOTXT%';

   IF l_num_errors <> 0
   THEN
      RAISE_APPLICATION_ERROR(-20001,'COMPILE ERROR');

   END IF;

   l_num_errors := DZ_SDOTXT_TEST.inmemory_test();

   IF l_num_errors <> 0
   THEN
      RAISE_APPLICATION_ERROR(-20001,'INMEMORY TEST ERROR');

   END IF;

END;
Error report -
ORA-20001: COMPILE ERROR
ORA-06512: at line 16

Do I need to install something in the database to be able to run the script?
As you may guess, I'm trying to export some MDSYS.SDO_GEOMETRY I have in my database, but it was imported from another DB directly using a DB link + INSERT INTO sentence.

**Comment by pauldzy** [comment]
Hi eyp,
My code is somewhat biased towards having a fully installed Oracle Spatial instance as defined in the 10g days.  It appears that your 11g instance is perhaps SE or had Spatial manually removed?

Regardless just comment out the offending code here
https://github.com/pauldzy/DZ_SDOTXT/blob/196a822ffacd03bd045d6dbb7545b511d957ba40/dz_sdotxt_deploy.sql#L853
in both the spec and body.  I can add more in-line comments if that is not clear.

I may need to consider how to make this code more friendly to Locator only users.  But its even more complicated than that.  For 12c and 18c its just a matter of enabling Georaster for the entire database via a one-time SYS call to **EXECUTE MDSYS.enableGeoRaster**.  But now 19c demands each schema using Georaster be enabled individually.  That makes it highly unlikely the "average person" will have access to Georaster objects.

If you send me a bit more info on your system and use case that would be helpful.
Thanks.

**Comment by eyp** [comment]
Ok, I also tried to execute the MDSYS.enableGeoRaster as SYSADMIN but no luck... for now I'm commenting out the functions that use SDO_GEORASTER and SDO_RASTER

**Comment by pauldzy** [comment]
Are you running Oracle EE or SE?

MDSYS.enableGeoRaster was added in 12c to make enabling the type easier.  If you are running EE then someone has specifically altered (neutered) your 11g database to remove your ability to use Georaster - probably as your organization does not have the full Oracle Spatial license.

I may need to break things out with a separate package for Georaster and two deployment scripts, one for a full traditional Oracle Spatial install and a second one for Locator only.

**Comment by eyp** [comment]
It's SE, installed in my dev environment. Finally I was able to deploy the scripts. If I execute this:
 
SELECT
dz_sdotxt_main.blob2plsql(
    dz_sdotxt_main.sdo2geomblob(a.shape)
) AS lob_text
FROM
ADIS_ZONES_R_TMP a
;

I get all the lines (it's a small table just for testing purposes). 

But If I try to get the inserts:
SELECT
dz_sdotxt_dumper(
   'SELECT * FROM ADIS_ZONES_R_TMP'
).sql_inserts('ADIS_ZONES_R') -- or plsql_inserts
FROM
dual;

I only get ONE line, the first row of the table. Any idea?

**Comment by eyp** [comment]
Forget it, it shows one line, but afterwards on edition mode it shows all the data! so it works!

**Comment by pauldzy** [comment]
Ahhh, SE.  So then by definition you only have Oracle Locator so do be aware anything using Oracle Spatial functionality will fail.  That needs EE and the Spatial option license.

This package was created primarily to pickle geospatial data into a compressed form you could paste into emails or github issue tickets.  If all you want to do is push SDO_GEOMETRY across a database link the easiest method is to use the undocumented SDO_UTIL.TO_CLOB and SDO_UTIL.FROM_CLOB directly. 

I'll create a ticket to better deal with the georaster issue as my expectation that users just have a full kit-and-caboodle Oracle Spatial installation is not really viable any longer.

Cheers,
Paul
